Remove "#include <gee.h>" from our external header file.

diff --git a/lib/click/valac-wrapper.in b/lib/click/valac-wrapper.in
--- a/lib/click/valac-wrapper.in
+++ b/lib/click/valac-wrapper.in
@@ -8,11 +8,15 @@ set -e
 #
 # Passing --shared-library to g-ir-compiler isn't enough for us, because
 # dh_girepository then fails to generate a shared library dependency.
+#
+# While we're here, work around <gee.h> showing up in our external header
+# file.  We're careful only to make use of it internally.
 
 VALAC="@VALAC@"
 
 "$VALAC" "$@"
 
+header=
 gir=
 library=
 
@@ -23,7 +27,8 @@ eval set -- "$(getopt -o CH: -l gir:,library:,pkg:,target-glib: -- "$@")" || \
 while :; do
 	case $1 in
 		-C) shift ;;
-		-H|--pkg|--target-glib) shift 2 ;;
+		-H) header="$2"; shift 2 ;;
+		--pkg|--target-glib) shift 2 ;;
 		--gir) gir="$2"; shift 2 ;;
 		--library) library="$2"; shift 2 ;;
 		--) shift; break ;;
@@ -31,9 +36,16 @@ while :; do
 	esac
 done
 
+[ "$header" ] || { echo "$0: failed to find -H in valac options" >&2; exit 2; }
 [ "$gir" ] || { echo "$0: failed to find --gir in valac options" >&2; exit 2; }
 [ "$library" ] || \
 	{ echo "$0: failed to find --library in valac options" >&2; exit 2; }
+
+if egrep 'Gee|gee_' "$header"; then
+	echo "libgee should not be exposed in our public header file." >&2
+	exit 1
+fi
+sed -i '/^#include <gee\.h>$/d' "$header"
 
 sed -i 's/\(<namespace .*version="[^"]*"\)/\1 shared-library="lib'"${library}"'.so.0"/' \
 	"$gir"
